#!/usr/bin/env python3
"""Wiki maintenance: index, hot cache, lint.

The wiki compounds only if something keeps it honest. Left alone, a markdown
knowledge base rots the same way every wiki rots: cross-references break, claims
go stale, pages orphan, and nobody notices until an answer is confidently wrong.

    python3 scripts/wiki.py index    # regenerate _index.md from the tree
    python3 scripts/wiki.py hot      # rebuild _hot.md, the ~500-token cache
    python3 scripts/wiki.py lint     # health check, exits 1 on findings
    python3 scripts/wiki.py all      # hot + index + lint

Pairs with scripts/memory-lint.py. Same job, different store.

Mechanical only. It cannot tell whether two pages contradict each other — that is
what the CONTESTED convention and a human read are for. What it can do is name
the pages worth reading.
"""

from __future__ import annotations

import re
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
KB = REPO / "knowledge"
WIKI = KB / "wiki"
QUESTIONS = KB / "questions"
DIGESTS = KB / "digests"
INDEX = KB / "_index.md"
HOT = KB / "_hot.md"
LOG = KB / "_log.md"

def open_questions():
    """Question files still unanswered. `status: answered` drops out of the lists
    but the file stays — the answer is the point of keeping it."""
    if not QUESTIONS.exists():
        return []
    return [q for q in sorted(QUESTIONS.glob("*.md"))
            if "status: answered" not in q.read_text()]


STALE_DAYS = 120        # a page nobody has touched in four months
MIN_LINKS = 3           # per knowledge/CLAUDE.md rule 3
HOT_BUDGET = 2000       # characters, roughly 500 tokens
RECENT_DAYS = 7


def pages() -> list[Path]:
    return sorted(WIKI.rglob("*.md")) if WIKI.exists() else []


def frontmatter(p: Path) -> dict:
    text = p.read_text(errors="replace")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out = {}
    for line in text[3:end].splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip()
    return out


def title_and_gist(p: Path) -> tuple[str, str]:
    title, gist = p.stem.replace("-", " "), ""
    body = p.read_text(errors="replace")
    if body.startswith("---"):
        body = body[body.find("\n---", 3) + 4:]
    for line in body.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("# ") and title == p.stem.replace("-", " "):
            title = s[2:].strip()
            continue
        if s.startswith(("#", ">", "|", "-", "*", "`", "_")):
            continue
        gist = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)
        gist = re.sub(r"[*_`]", "", gist).split(". ")[0].strip().rstrip(".")
        break
    return title, gist[:150]


def links_in(p: Path) -> list[str]:
    """Relative markdown links plus [[wikilinks]] — Obsidian may write either."""
    text = p.read_text(errors="replace")
    found = [t.split("#")[0].strip() for t in re.findall(r"\]\(([^)]+)\)", text)]
    found = [t for t in found if t and not t.startswith(("http://", "https://", "mailto:"))]
    found += [f"{w}.md" for w in re.findall(r"\[\[([^\]]+)\]\]", text)]
    return found


def git_days_since(p: Path) -> int | None:
    """Days since last change. Falls back to filesystem mtime.

    An uncommitted page has no git history, and those are the newest — the ones
    the hot cache most needs to show. Trusting git alone made brand-new pages
    invisible to `hot` and immune to the stale check at the same time.
    """
    out = subprocess.run(
        ["git", "-C", str(REPO), "log", "-1", "--format=%ct", "--", str(p)],
        capture_output=True, text=True,
    )
    ts = out.stdout.strip()
    when = (datetime.fromtimestamp(int(ts), tz=timezone.utc) if ts
            else datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc))
    return (datetime.now(timezone.utc) - when).days


# ------------------------------------------------------------------- commands

def build_index() -> None:
    by_topic: dict[str, list[Path]] = defaultdict(list)
    for p in pages():
        by_topic[frontmatter(p).get("topic", "untagged")].append(p)

    total = sum(len(v) for v in by_topic.values())
    lines = [
        "# Index — every page in the wiki",
        "",
        "Generated by `python3 scripts/wiki.py index`. Do not hand-edit.",
        "",
        f"_{total} pages, last built {datetime.now().strftime('%Y-%m-%d')}._",
        "",
        "Protocol: [CLAUDE.md](./CLAUDE.md) · Active state: [_hot.md](./_hot.md) "
        "· History: [_log.md](./_log.md)",
        "",
    ]
    for topic in sorted(by_topic):
        lines += [f"## {topic}", ""]
        for p in sorted(by_topic[topic]):
            title, gist = title_and_gist(p)
            rel = p.relative_to(KB)
            lines.append(f"- [{title}](./{rel})" + (f" — {gist}" if gist else ""))
        lines.append("")

    open_qs = open_questions()
    if open_qs:
        lines += ["## open questions", ""]
        for q in open_qs:
            title, _ = title_and_gist(q)
            lines.append(f"- [{title}](./{q.relative_to(KB)})")
        lines.append("")

    INDEX.write_text("\n".join(lines))
    print(f"_index.md: {total} pages, {len(by_topic)} topics, {len(open_qs)} open questions")


def build_hot() -> None:
    """The ~500-token cache an agent reads BEFORE crawling the wiki.

    Everything here is derived, so it can never drift from reality: recently
    touched pages come from git, open questions from the folder, the last few
    log lines from the log itself.
    """
    recent = []
    for p in pages():
        d = git_days_since(p)
        if d is not None and d <= RECENT_DAYS:
            recent.append((d, p))
    recent.sort()

    open_qs = open_questions()
    log_tail = []
    if LOG.exists():
        log_tail = [l for l in LOG.read_text().splitlines() if l.strip().startswith("20")][-5:]

    out = [
        "# Hot — what is active right now",
        "",
        "Generated by `python3 scripts/wiki.py hot`. **Read this before crawling "
        "the wiki.** It is the cheapest way to know where things stand.",
        "",
        f"_Rebuilt {datetime.now().strftime('%Y-%m-%d')}._",
        "",
    ]

    if recent:
        out += [f"## Touched in the last {RECENT_DAYS} days", ""]
        for days, p in recent[:12]:
            title, _ = title_and_gist(p)
            when = "today" if days == 0 else f"{days}d ago"
            out.append(f"- [{title}](./{p.relative_to(KB)}) — {when}")
        out.append("")
    else:
        out += ["## Touched in the last week", "", "Nothing. The wiki is idle.", ""]

    if open_qs:
        out += ["## Open questions", ""]
        for q in open_qs[:8]:
            title, _ = title_and_gist(q)
            out.append(f"- [{title}](./{q.relative_to(KB)})")
        out.append("")

    if log_tail:
        out += ["## Last few operations", ""] + [f"- {l}" for l in reversed(log_tail)] + [""]

    text = "\n".join(out)
    if len(text) > HOT_BUDGET:
        text = text[:HOT_BUDGET].rsplit("\n", 1)[0] + "\n\n_(truncated to stay cheap)_\n"
    HOT.write_text(text)
    print(f"_hot.md: {len(recent)} recent, {len(open_qs)} questions, {len(text)} chars")


def lint() -> int:
    all_pages = pages()
    findings: list[str] = []

    if not all_pages:
        print("wiki lint: no pages yet — nothing to check")
        return 0

    rels = {p.relative_to(KB) for p in all_pages}
    inbound: dict[Path, int] = {r: 0 for r in rels}

    for p in all_pages:
        rel = p.relative_to(KB)
        targets = links_in(p)
        for t in targets:
            resolved = (p.parent / t).resolve()
            if not resolved.exists():
                resolved = (WIKI / t).resolve()
            try:
                tr = resolved.relative_to(KB)
            except ValueError:
                continue
            if resolved.exists():
                if tr in inbound:
                    inbound[tr] += 1
            elif t.endswith(".md"):
                findings.append(f"BROKEN LINK   {rel} -> {t}")

        internal = [t for t in targets if t.endswith(".md") and "raw/" not in t]
        if len(internal) < MIN_LINKS:
            findings.append(
                f"THIN LINKS    {rel} has {len(internal)} links, minimum is "
                f"{MIN_LINKS} — this is what keeps the graph a cloud of dots")

        fm = frontmatter(p)
        if "topic" not in fm:
            findings.append(f"NO TOPIC      {rel} has no topic: in frontmatter")

    for rel, n in sorted(inbound.items()):
        if n == 0:
            findings.append(f"ORPHAN        {rel} (nothing links to it)")

    titles: dict[str, list[Path]] = defaultdict(list)
    for p in all_pages:
        titles[title_and_gist(p)[0].lower()].append(p.relative_to(KB))
    for t, paths in sorted(titles.items()):
        if len(paths) > 1:
            findings.append(f"DUPLICATE     '{t}' is the title of {len(paths)} pages: "
                            + ", ".join(str(x) for x in paths))

    for p in all_pages:
        days = git_days_since(p)
        if days is not None and days > STALE_DAYS:
            findings.append(f"STALE         {p.relative_to(KB)} untouched {days} days")

    if QUESTIONS.exists():
        for q in QUESTIONS.glob("*.md"):
            days = git_days_since(q)
            if days is not None and days > STALE_DAYS:
                findings.append(f"OLD QUESTION  {q.name} open {days} days — answer it or kill it")

    before = INDEX.read_text() if INDEX.exists() else ""
    build_index()
    if INDEX.read_text() != before:
        findings.append("INDEX         _index.md was out of date — regenerated")

    if not findings:
        print("wiki lint: clean")
        return 0
    for f in findings:
        print(f)
    print(f"\n{len(findings)} findings.")
    print("Mechanical only. CONTESTED blocks and whether a page is still TRUE need")
    print("a human read — start with the STALE and DUPLICATE lines.")
    return 1


def eval_results(path: str) -> int:
    """Verify every page an eval answer cited actually exists.

    The 'cited' check in knowledge/evals/questions.md is the only one of the
    three a script can settle. Grounded and honest need a human read — a citation
    to a real page proves nothing about whether the claim came from it.
    """
    p = Path(path)
    if not p.exists():
        print(f"no results file at {path}")
        return 1

    bad, total = [], 0
    for target in links_in(p):
        if not target.endswith(".md"):
            continue
        total += 1
        # Try the link as written, then by basename. A results file can sit
        # anywhere, so a relative path that does not resolve from here is not
        # proof the page is fake — only a missing basename is.
        name = target.split("/")[-1]
        found = any((base / target).resolve().exists() for base in (p.parent, KB, REPO))
        found = found or any((d / name).exists() for d in (WIKI, QUESTIONS, KB))
        if not found:
            bad.append(target)

    if not total:
        print("no page citations found — an eval answer with zero citations "
              "fails the 'cited' check by definition")
        return 1
    if bad:
        print(f"HALLUCINATED CITATIONS ({len(bad)} of {total}):")
        for b in bad:
            print(f"  {b}")
        print("\nAn answer citing a page that does not exist is the failure this "
              "check exists to catch. Score those answers 0 on 'cited'.")
        return 1
    print(f"citations: {total} checked, all resolve")
    return 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "eval":
        if len(sys.argv) < 3:
            sys.exit("usage: wiki.py eval knowledge/evals/results/YYYY-MM.md")
        sys.exit(eval_results(sys.argv[2]))
    elif cmd == "index":
        build_index()
    elif cmd == "hot":
        build_hot()
    elif cmd == "lint":
        sys.exit(lint())
    elif cmd == "all":
        build_hot()
        sys.exit(lint())
    else:
        sys.exit(__doc__)
